name: Mini CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:    # Manual trigger

env:
  APP_ENV: "dev"
  BUILD_DIR: "dist"

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout code ---
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- Setup Node.js ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # --- Install dependencies ---
      - name: Install Dependencies
        run: npm install

      # --- Build the app ---
      - name: Build
        run: npm run build

      # --- Run Tests ---
      - name: Test
        run: npm run test

      # --- Use Secret ---
      - name: Display secret safely
        run: |
          echo "App environment is $APP_ENV"
          echo "Secret from GitHub is ${{ secrets.MY_SECRET }}"
      
      # --- Upload artifact (build output) ---
      - name: Create dummy build folder
        run: |
          mkdir -p $BUILD_DIR
          echo "build completed at $(date)" > $BUILD_DIR/build-info.txt

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ env.BUILD_DIR }}
